name: Save Changes on Push

on:
  push:
    branches:
      - main  # 주요 브랜치에서만 실행

jobs:
  save-changes:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 커밋 데이터를 가져옴 (diff를 위해 필수)

      # 2. 변경 정보 저장
      - name: Save changes
        run: |
          echo "Collecting changes..."

          # 변경된 파일 목록 저장
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          
          # 변경된 파일 내용 저장
          git diff ${{ github.event.before }} ${{ github.sha }} > changes_with_diffs.txt

          # 변경된 정보를 저장할 디렉토리 생성
          mkdir -p diff-info

          # 결과 파일 이동
          mv changed_files.txt diff-info/
          mv changes_with_diffs.txt diff-info/

          # 파일명 출력
          echo "Files created:"
          ls -l diff-info/

          # 파일 내용 출력
          echo "=== Changed Files ==="
          cat diff-info/changed_files.txt || echo "No files changed."

          echo "=== Changes with Diffs ==="
          cat diff-info/changes_with_diffs.txt || echo "No diff content."
