name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-24.04
    steps:
      - run: ls -al # 현재 디렉토리 내용 출력
      - uses: actions/checkout@v3
      
      - run: ls -al # 작업 디렉토리 내의 파일을 나열
      - run: cat .github/workflows/checkout.yml # 워크플로우 YAML 파일의 내용을 출력