name: Save Changes and Run Python Script

on:
  push:
    branches:
      - main  # 주요 브랜치에서만 실행

jobs:
  save-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 커밋 데이터를 가져옴 (diff를 위해 필수)

      # 2. 변경된 파일 및 내용 저장
      - name: Save changes
        run: |
          echo "Collecting changes..."

          # diff-info 디렉토리 생성
          mkdir -p diff-info

          # 변경된 파일 목록 저장
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > diff-info/changed_files.txt
          
          # 각 파일의 변경 사항을 파일별로 저장
          while read file; do
            echo "Saving changes for file: $file"
            git diff ${{ github.event.before }} ${{ github.sha }} -- $file > "diff-info/${file//\//_}.diff"
          done < diff-info/changed_files.txt

      # 3. 필요한 Python 패키지 설치
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      # 4. Python 스크립트 실행
      - name: Run Python Script
        run: |
          echo "Running Python script..."
          python3 process_changes.py diff-info/changed_files.txt diff-info/

      # 5. 새로운 Python 스크립트 실행
      - name: Run New Python Script
        run: |
          echo "Running new Python script..."
          python3 notion_upload.py diff-info/
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.TEST_DATABASE_ID }}
