name: Check Changes on Commit
env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main  # 주요 브랜치에서만 실행

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: tj-actions/changed-files@v44
        with:
          fetch-depth: 0  # 모든 커밋을 가져와야 이전 커밋에 접근 가능

      # 2. 변경 사항 확인
      - name: Get changes
        run: |
          if [[ "${{ github.event.before }}" == "00000000000000000000000000000" ]]; then
            echo "This is the first commit or a new branch creation. Skipping diff."
          else
            echo "Previous commit: ${{ github.event.before }}"
            echo "Current commit: ${{ github.sha }}"

            # 변경 파일 목록 가져오기
            git diff --name-only ${{ github.event.before }} ${{ github.sha }}

            # 변경된 파일 내용 가져오기 (선택 사항)
            git diff ${{ github.event.before }} ${{ github.sha }}

            # 변경된 파일 목록을 로그에 출력
            echo "Changed files:"
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tee changed_files.txt
          fi
