name: Check Changes on Commit

on:
  push:
    branches:
      - main  # 주요 브랜치에서만 실행

jobs:
  check-changes:
    runs-on: ubuntu-24.04

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 커밋을 가져옴

      # 2. 변경 파일 확인
      - name: Check changes
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          path: ${{ github.workspace }}

      # 3. 변경된 파일 목록 출력
      - name: Show changed files
        run: |
          echo "Changed files:"
          echo "${{ steps.changes.outputs.files }}"