name: Save Changes and Run Python Script

on:
  push:
    branches:
      - main  # 주요 브랜치에서만 실행

jobs:
  save-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 변경된 파일 및 내용 저장
      - name: Save changes
        run: |
          echo "Collecting changes..."

          # 변경된 파일 목록 저장
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          
          # 변경된 파일 내용 저장
          git diff ${{ github.event.before }} ${{ github.sha }} > changes_with_diffs.txt

          # 변경된 정보를 저장할 디렉토리 생성
          mkdir -p diff-info

          # 결과 파일 이동
          mv changed_files.txt diff-info/
          mv changes_with_diffs.txt diff-info/

      # 3. Python 스크립트 실행
      - name: Run Python Script
        run: |
          echo "Running Python script..."
          python3 process_changes.py diff-info/changed_files.txt diff-info/changes_with_diffs.txt

      # 4. 변경된 파일 확인 (디버깅용 로그)
      - name: Output Debug Info
        run: |
          echo "Changed Files:"
          cat diff-info/changed_files.txt
          echo "Changes with Diffs:"
          cat diff-info/changes_with_diffs.txt
